# Generated by Django 4.2.30 on 2026-06-15 10:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_seed_worlds'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardRank',
            fields=[
                ('rank', models.IntegerField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(db_index=True, max_length=32)),
                ('best_score', models.IntegerField(default=0)),
                ('total_runs', models.IntegerField(default=0)),
                ('avg_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leaderboard_ranks',
                'ordering': ['rank'],
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='achievement',
            name='achievement_type',
            field=models.CharField(choices=[('GRADUATE', 'Boot Camp Graduate'), ('SCORE', 'Score Milestone'), ('LEVEL', 'Level Milestone'), ('ENEMIES', 'Enemies Killed'), ('WORLD', 'World Complete')], default='SCORE', max_length=20),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='is_tutorial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='tutorial_objectives_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='boot_camp_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries_legacy', to='game.player'),
        ),
        migrations.CreateModel(
            name='ScoreSubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_hash', models.CharField(blank=True, default='', help_text='Hashed IP for additional rate-limiting', max_length=64)),
                ('score', models.IntegerField(default=0)),
                ('accepted', models.BooleanField(default=True)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=100)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_logs', to='game.player')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['player', '-submitted_at'], name='game_scores_player__44763b_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_name', models.CharField(db_index=True, help_text='Denormalized for speed', max_length=32)),
                ('score', models.IntegerField(db_index=True, default=0)),
                ('level_id', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('character_used', models.CharField(default='', max_length=32)),
                ('duration_sec', models.IntegerField(default=0)),
                ('accuracy_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('enemies_killed', models.IntegerField(default=0)),
                ('powerups_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_pb', models.BooleanField(default=False, help_text='True if this run is a personal best')),
                ('replay_hash', models.CharField(blank=True, default='', help_text='Deterministic hash of inputs for anti-cheat verification', max_length=64)),
                ('verified', models.BooleanField(default=False, help_text='True if replay hash verified')),
                ('flagged', models.BooleanField(default=False, help_text='True if score flagged for manual review')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries_v2', to='game.player')),
                ('world', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.world')),
            ],
            options={
                'ordering': ['-score', 'created_at'],
                'indexes': [models.Index(fields=['player', '-score'], name='game_leader_player__cb9e4c_idx'), models.Index(fields=['world', '-score'], name='game_leader_world_i_655f60_idx'), models.Index(fields=['created_at'], name='game_leader_created_5b48df_idx')],
            },
        ),
    ]
