# Generated by Django 4.2.30 on 2026-07-02 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_leaderboardentry_game_world_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leaderboardentry',
            new_name='game_leader_game_wo_fdbeff_idx',
            old_name='game_leaderb_game_wo_idx',
        ),
    ]
