# Generated by Django 4.2.30 on 2026-07-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_rename_game_leaderb_game_wo_idx_game_leader_game_wo_fdbeff_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='progression',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
